from pathlib import Path
import subprocess


here = Path(__file__).resolve().parent
source = here.parent.parent / "outputs" / "BonRaffle-WinUI-2.2.26"
if not (source / "Bon Raffle.exe").is_file():
    raise SystemExit("Bon Raffle.exe is missing from the release")

files = sorted(
    (p for p in source.rglob("*") if p.is_file() and p.suffix.lower() != ".pdb"),
    key=lambda p: p.relative_to(source).as_posix().lower(),
)
directories = sorted(
    (p for p in source.rglob("*") if p.is_dir()),
    key=lambda p: (-len(p.relative_to(source).parts), p.relative_to(source).as_posix().lower()),
)


def nsis_path(path: Path) -> str:
    relative = str(path.relative_to(source)).replace("/", "\\")
    if "$" in relative or '"' in relative:
        raise ValueError(f"Unsafe NSIS path: {relative}")
    return "$INSTDIR\\" + relative


lines = ["; Generated by build_installer.py; remove only files that this build installs."]
lines.extend(f'    Delete "{nsis_path(p)}"' for p in files)
lines.extend(f'    RMDir "{nsis_path(p)}"' for p in directories)
(here / "UninstallFiles.nsh").write_text("\n".join(lines) + "\n", encoding="utf-8-sig")

makensis = Path(r"C:\Program Files (x86)\NSIS\makensis.exe")
subprocess.run([str(makensis), "/V2", "/WX", "BonRaffle.nsi"], cwd=here, check=True)
